devices:
  - name: "TX-81z"
    outputMidiDevice: "M8U eX 15"
    inputMidiDevice: "M8U eX 16"

translate:
  fromMidiDevice: "4- MIDISPORT Uno In"
  toDevice: "TX-81z"
# Translation rules:
# use vv to inject the control change value inside the SYSEX
# use [low,high] to rescale the input value
translations:
  - 7 => OP1_FREQ(vv) [0,63] # convert CC Volume (7) in the range [0-127] to some TX81z parameters in the range [0,63]
