---
selectedOutput: null
selectedInputs:
- "FromDAW"
selectedSecondaryOutputs:
- "FromDAW"
selectedPatches:
- device: "TG-33"
  mode: "Voice"
  bank: "Preset 2 Voices"
  name: "BA:Pick"
  category: "Bass"
  command: "000514"
  filename: null
  channel: 0
  score: 0
- device: "Summit"
  mode: "Single"
  bank: "Bank B"
  name: "10p Ice Pops"
  category: "Keyboard"
  command: "00026E"
  filename: null
  channel: 0
  score: 0
- device: "Mininova"
  mode: "Single"
  bank: "Bank A"
  name: "AlaskaSplitLoC"
  category: "Classic"
  command: "0145"
  filename: null
  channel: 0
  score: 2
- device: "DS-330"
  mode: "GS Standard"
  bank: "SC"
  name: "5th Saw Wave"
  category: "Synth lead"
  command: "0056"
  filename: null
  channel: 1
  score: 0
- device: "JV-880"
  mode: "Performance"
  bank: "Internal Bank"
  name: "Encounter X"
  category: "Unknown"
  command: "5001"
  filename: null
  channel: 0
  score: 0
- device: "DS-330"
  mode: "GS Standard"
  bank: "SC"
  name: "Agogo"
  category: "Percussive"
  command: "0071"
  filename: null
  channel: 0
  score: 0
- device: "TG-500"
  mode: "Voice"
  bank: "Preset 1 Voices"
  name: "AP Grand"
  category: "Piano"
  command: "000200"
  filename: null
  channel: 0
  score: 0
- device: "CS1x"
  mode: "XG"
  bank: "XG 037 (5th 1)"
  name: "60's Drawbar Organ 3"
  category: "Organ"
  command: "002510"
  filename: null
  channel: 1
  score: 0
- device: "CS1x"
  mode: "Performance"
  bank: "Performances"
  name: "Airy"
  category: "Synth FX"
  command: "3F401F"
  filename: null
  channel: 0
  score: 5
- device: "M1 VST"
  mode: "Program"
  bank: "06 MPC-04 ORCHESTRA 1"
  name: "BreathBass"
  category: "Bass"
  command: "000624"
  filename: null
  channel: 0
  score: 0
- device: "CS1x"
  mode: "XG"
  bank: "XG 035 (Octave 1)"
  name: "70's Drawbar Organ 1"
  category: "Organ"
  command: "002310"
  filename: null
  channel: 0
  score: 0
