---
selectedPatches:
- device: "QS6.1"
  mode: "ProgramMode"
  bank: "Bank 2"
  name: "LegatoAGtr"
  category: "Guitar"
  command: "2-30"
- device: "Summit"
  mode: "SingleMode"
  bank: "Bank C"
  name: "Fantasoba"
  category: "Synth Poly"
  command: "0-3-40"
