---
selectedPatches:
  Summit:
    mode: "SingleMode"
    bank: "Bank C"
    name: "Ambi Sludge Pro"
    category: "Synth Pad"
    command: "0-3-115"
  Mininova:
    mode: "SingleMode"
    bank: "Bank A"
    name: "Shufflin DF"
    category: "Motion Synth"
    command: "1-9"
