---
selectedOutput: null
selectedInputs:
- "Summit"
selectedSecondaryOutputs:
- "Summit"
selectedPatches:
- device: "TG-33"
  mode: "Voice"
  bank: "Preset 2 Voices"
  name: "BA:Pick"
  category: "Bass"
  command: "000514"
  filename: null
  channel: 0
  score: 0
- device: "Summit"
  mode: "Single"
  bank: "Bank B"
  name: "10p Ice Pops"
  category: "Keyboard"
  command: "00026E"
  filename: null
  channel: 0
  score: 0
- device: "DS-330"
  mode: "GS Standard"
  bank: "SC"
  name: "5th Saw Wave"
  category: "Synth lead"
  command: "0056"
  filename: null
  channel: 1
  score: 0
- device: "DS-330"
  mode: "GS Standard"
  bank: "SC"
  name: "Agogo"
  category: "Percussive"
  command: "0071"
  filename: null
  channel: 0
  score: 0
- device: "CS1x"
  mode: "XG"
  bank: "XG 037 (5th 1)"
  name: "60's Drawbar Organ 3"
  category: "Organ"
  command: "002510"
  filename: null
  channel: 1
  score: 0
- device: "CS1x"
  mode: "Performance"
  bank: "Performances"
  name: "Airy"
  category: "Synth FX"
  command: "3F401F"
  filename: null
  channel: 0
  score: 5
- device: "M1 VST"
  mode: "Program"
  bank: "22 LEGACY COLLECTION PRESETS"
  name: "4th SEQ Syn"
  category: "Synth Lead"
  command: "001555"
  filename: null
  channel: 0
  score: 0
- device: "AN1x"
  mode: "Voice"
  bank: "Voices"
  name: "CS80 Brass"
  category: "Brass"
  command: "2D"
  filename: null
  channel: 0
  score: 4
- device: "CS1x"
  mode: "XG"
  bank: "XG 064 (Other waves 1)"
  name: "60's Electric Piano 1"
  category: "Piano"
  command: "004004"
  filename: null
  channel: 0
  score: 0
- device: "TG-500"
  mode: "Voice"
  bank: "Top40"
  name: "AP Brght.syx"
  category: "Ethnic"
  command: "000000"
  filename: "001 [000000,Ethnic] AP Brght.syx"
  channel: 0
  score: 0
- device: "Mininova"
  mode: "Single"
  bank: "UNDF-Vol2-b"
  name: "()UltraGasm() DF.syx"
  category: "None"
  command: null
  filename: "029 [None] ()UltraGasm() DF.syx"
  channel: 0
  score: 0
- device: "Micron"
  mode: "Program"
  bank: "Edit Bank"
  name: "+Bass2 timfloy"
  category: "Bass"
  command: "000449"
  filename: null
  channel: 0
  score: 0
- device: "N1R"
  mode: "Multi"
  bank: "CmbB"
  name: "12 Stereo"
  category: "Unknown"
  command: "5A0022"
  filename: null
  channel: 0
  score: 0
- device: "JV-880"
  mode: "Performance"
  bank: "Preset A Bank"
  name: "Bossa nova"
  category: "Unknown"
  command: "5102"
  filename: null
  channel: 0
  score: 0
