# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Native build

on:
  workflow_dispatch:

jobs:
  workshop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Jar Build with Maven
        run: mvn clean install --file pom.xml -DskipTests
      - name: Native Build Synth-ripper with Maven
        run: mvn -Pnative native:compile --file synth-ripper/pom.xml -DskipTests
      - name: Native Build Midi-Translator with Maven
        run: mvn -Pnative native:compile --file midi-translator/pom.xml -DskipTests
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'macOS' }}
        with:
          name: synth-ripper-osx
          path: |
            synth-ripper/target/synth-ripper
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: synth-ripper-x64.exe
          path: |
            synth-ripper/target/synth-ripper.exe
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: synth-ripper.jar
          path: |
            synth-ripper/target/synth-ripper*.jar            
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'macOS' }}
        with:
          name: midi-translator-osx
          path: |
            midi-translator/target/midi-translator
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: midi-translator-x64.exe
          path: |
            midi-translator/target/midi-translator.exe
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: midi-translator.jar
          path: |
            midi-translator/target/midi-translator*.jar
  
