# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release build

on:
  workflow_dispatch:

jobs:
  workshop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Jar Build with Maven
        run: mvn clean install --file pom.xml -DskipTests
      - name: Native Build Synth-ripper with Maven
        run: mvn -Pnative native:compile --file synth-ripper/pom.xml -DskipTests
      - name: Native Build midi-backup-translator with Maven
        run: mvn -Pnative native:compile --file midi-backup-translator/pom.xml -DskipTests
      #
      # midi-backup-translator
      #
      - name: Prepare midi-backup-translator distrib
        run: |
          cp midi-backup-translator/doc/readme.pdf midi-backup-translator/target
          cp -R midi-backup-translator/config/config-example.yml midi-backup-translator/target/config-example.yml
          cp -R midi-backup-translator/devices midi-backup-translator/target
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: midi-backup-translator-x64
          path: |
            midi-backup-translator/target/midi-backup-translator.exe
            midi-backup-translator/target/jsound.dll
            midi-backup-translator/target/config-example.yml
            midi-backup-translator/target/devices
            midi-backup-translator/target/readme.pdf
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'macOS' }}
        with:
          name: midi-backup-translator-osx
          path: |
            midi-backup-translator/target/midi-backup-translator
            midi-backup-translator/target/config-example.yml
            midi-backup-translator/target/devices
            midi-backup-translator/target/readme.pdf
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: midi-backup-translator-jvm
          path: |
            midi-backup-translator/target/midi-backup-translator*.jar
            midi-backup-translator/target/config-example.yml
            midi-backup-translator/target/devices
            midi-backup-translator/target/readme.pdf
      #
      # synth-ripper
      #
      - name: Prepare synth-ripper distrib
        run: |
          ls -la synth-ripper/target
          cp synth-ripper/doc/readme.txt synth-ripper/target
          cp -R synth-ripper/config synth-ripper/target
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: synth-ripper-x64
          path: |
            synth-ripper/target/synth-ripper.exe
            synth-ripper/target/jsound.dll
            synth-ripper/target/config
            synth-ripper/target/readme.txt
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'macOS' }}
        with:
          name: synth-ripper-osx
          path: |
            synth-ripper/target/synth-ripper
            synth-ripper/target/config
            synth-ripper/target/readme.txt
      - uses: actions/upload-artifact@v4
        if: ${{ runner.os == 'Windows' }}
        with:
          name: synth-ripper-jdk
          path: |
            synth-ripper/target/synth-ripper*.jar
            synth-ripper/target/config
            synth-ripper/target/readme.txt            
